// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "io.shiftleft:gather-dependencies:0.5"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
           url = "https://no.such.url/gradle/libs-releases/"
           // vulnerability: Hardcoded Credentials
           credentials {
                username = "barnabyjack"
                password = "PhitiTeeLiethi0eephi"
           }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

